import React, { useEffect, useMemo, useState } from 'react';
import { Bookmark, ExternalLink, X } from 'lucide-react';
import { monitoringStore } from '@/lib/monitoring-service';

export default function LiveIntelligenceFeed() {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState('all'); const refresh = () => setItems(monitoringStore.discoveries());
  useEffect(() => { refresh(); return monitoringStore.subscribe(refresh); }, []);
  const visible = useMemo(() => items.filter(x => !x.dismissed && (filter === 'all' || x.type === filter)).sort((a, b) => ({ HIGH: 3, MEDIUM: 2, LOW: 1 }[b.priority] - { HIGH: 3, MEDIUM: 2, LOW: 1 }[a.priority])), [items, filter]);
  return <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-heading text-lg font-bold">Live Intelligence Feed</h2><p className="text-xs text-muted-foreground">Stored discoveries from your manual watchlist checks. Signal scores use record activity and recency; they are not quality ratings.</p></div><div className="flex gap-1">{['all','paper','researcher','institution','opportunity'].map(x => <button key={x} onClick={() => setFilter(x)} className={`rounded-lg px-2.5 py-1.5 text-[10px] font-semibold capitalize ${filter === x ? 'bg-primary text-white' : 'bg-secondary text-muted-foreground'}`}>{x}</button>)}</div></div>{visible.length ? <div className="space-y-3">{visible.map(item => <article key={item.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex gap-4"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap gap-2"><span className="rounded-full bg-primary/10 px-2 py-1 text-[9px] font-bold text-primary">{item.type}</span><span className="rounded-full bg-secondary px-2 py-1 text-[9px] font-bold">{item.priority}</span><span className="text-[10px] text-muted-foreground">Signal {item.confidenceScore}%</span></div><h3 className="font-heading font-semibold">{item.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{item.description || item.evidence}</p><details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold text-primary">Evidence & recommended action</summary><p className="mt-2 text-muted-foreground">{item.evidence}</p><p className="mt-1 text-muted-foreground">{item.recommendedAction}</p></details></div><div className="flex flex-col gap-1"><button onClick={() => monitoringStore.updateDiscovery(item.id, { saved: !item.saved })} className={`p-2 ${item.saved ? 'text-primary' : 'text-muted-foreground'}`} aria-label="Save"><Bookmark size={14} fill={item.saved ? 'currentColor' : 'none'} /></button><button onClick={() => monitoringStore.updateDiscovery(item.id, { dismissed: true })} className="p-2 text-muted-foreground" aria-label="Dismiss"><X size={14} /></button><a href={item.sourceUrl} target="_blank" rel="noreferrer" className="p-2 text-primary" aria-label="Open source"><ExternalLink size={14} /></a></div></div></article>)}</div> : <div className="rounded-2xl border border-dashed border-border py-12 text-center text-sm text-muted-foreground">No stored discoveries yet. Add a watchlist and check for updates.</div>}</section>;
}
