import React, { useEffect, useState } from 'react';
import { Bell, CheckCheck, ExternalLink, Trash2 } from 'lucide-react';
import { monitoringStore } from '@/lib/monitoring-service';

export default function Notifications() {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState('all'); const refresh = () => setItems(monitoringStore.notifications());
  useEffect(() => { refresh(); return monitoringStore.subscribe(refresh); }, []);
  const shown = items.filter(item => filter === 'all' || (filter === 'unread' ? !item.read : item.type === filter));
  return <div className="mx-auto max-w-4xl px-4 py-10"><div className="mb-7 flex items-center justify-between gap-4"><div><div className="flex items-center gap-2"><Bell size={19} className="text-primary" /><h1 className="font-heading text-2xl font-bold">Notifications</h1></div><p className="mt-1 text-sm text-muted-foreground">High-priority findings from your EYRA watchlists.</p></div><button onClick={() => monitoringStore.markAllRead()} className="flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-xs font-semibold"><CheckCheck size={13} />Mark all read</button></div><div className="mb-5 flex gap-2">{['all','unread','paper','researcher','institution'].map(x => <button key={x} onClick={() => setFilter(x)} className={`rounded-lg px-3 py-2 text-xs capitalize ${filter === x ? 'bg-primary text-white' : 'bg-secondary text-muted-foreground'}`}>{x}</button>)}</div><div className="space-y-3">{shown.map(item => <article key={item.id} className={`rounded-2xl border border-border p-5 ${item.read ? 'bg-card/50' : 'bg-primary/5'}`}><div className="flex gap-4"><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-wider text-primary">{item.priority} · {item.type}</p><h2 className="mt-1 font-heading font-semibold">{item.title}</h2><p className="mt-2 text-xs text-muted-foreground">{item.description}</p></div><div className="flex gap-1"><a href={item.sourceUrl} target="_blank" rel="noreferrer" onClick={() => monitoringStore.markNotification(item.id, { read: true })} className="p-2 text-primary"><ExternalLink size={14} /></a><button onClick={() => monitoringStore.markNotification(item.id, { dismissed: true, read: true })} className="p-2 text-muted-foreground"><Trash2 size={14} /></button></div></div></article>)}{!shown.length && <p className="rounded-2xl border border-dashed border-border py-12 text-center text-sm text-muted-foreground">No notifications in this view.</p>}</div></div>;
}
