import React from 'react';

const EYRA_LOGO = "https://media.base44.com/images/public/6a3b660e73254d1b4bf55bcb/33f475246_image.png";
const EYRA_FULL_LOGO = "https://media.base44.com/images/public/6a3b660e73254d1b4bf55bcb/9564f1a19_ChatGPTImage22202612_00_48.png";

/**
 * EyraBadge — reusable EYRA branding badge.
 * variant: "powered" | "analyzed" | "recommended" | "discovered" | "monitored" | "generated" | "inline"
 * size: "sm" | "md"
 */
export default function EyraBadge({ variant = 'powered', size = 'sm', className = '' }) {
  const labels = {
    powered: 'Powered by EYRA',
    analyzed: 'Analyzed by EYRA',
    recommended: 'Recommended by EYRA',
    discovered: 'Discovered by EYRA',
    monitored: 'Monitored by EYRA',
    generated: 'Generated by EYRA',
    intelligence: 'EYRA Intelligence',
    twin: 'EYRA Project Twin',
    inline: 'EYRA',
  };

  const label = labels[variant] || labels.powered;
  const isSmall = size === 'sm';

  return (
    <span className={`inline-flex items-center gap-1.5 ${isSmall ? 'text-[10px]' : 'text-xs'} font-semibold text-primary/80 ${className}`}>
      <img src={EYRA_LOGO} alt="EYRA" className={isSmall ? 'h-3 w-auto' : 'h-3.5 w-auto'} style={{ objectFit: 'contain' }} />
      {label}
    </span>
  );
}

/** Standalone "Powered by EYRA" footer line — use under search boxes, results, etc. */
export function EyraPoweredBy({ label = 'Powered by EYRA', className = '' }) {
  return (
    <div className={`flex items-center justify-center gap-1.5 ${className}`}>
      <img
        src={EYRA_LOGO}
        alt="EYRA"
        className="h-3 w-auto opacity-60"
        style={{ objectFit: 'contain' }}
      />
      <span className="text-[10px] text-muted-foreground/60 font-medium tracking-wide">{label}</span>
    </div>
  );
}

/** Section header label — "EYRA Funding Intelligence", "EYRA Project Twin", etc. */
export function EyraSectionLabel({ label, className = '' }) {
  return (
    <div className={`flex items-center gap-2 ${className}`}>
      <img src={EYRA_LOGO} alt="EYRA" className="h-4 w-auto" style={{ objectFit: 'contain' }} />
      <span className="text-[10px] font-bold uppercase tracking-widest text-primary">{label}</span>
    </div>
  );
}
