import React from 'react';
import { EyraOrb } from '@/components/brand/BrandLogo';

/**
 * EyraBadge — reusable EYRA branding badge.
 * variant: "powered" | "analyzed" | "recommended" | "discovered" | "monitored" | "generated" | "inline"
 * size: "sm" | "md"
 */
export default function EyraBadge({ variant = 'powered', size = 'sm', className = '' }) {
  const labels = {
    powered: 'Powered by EYRA',
    analyzed: 'Analyzed by EYRA',
    recommended: 'Recommended by EYRA',
    discovered: 'Discovered by EYRA',
    monitored: 'Monitored by EYRA',
    generated: 'Generated by EYRA',
    intelligence: 'EYRA Intelligence',
    twin: 'EYRA Project Twin',
    inline: 'EYRA',
  };

  const label = labels[variant] || labels.powered;
  const isSmall = size === 'sm';

  return (
    <span className={`inline-flex items-center gap-1.5 ${isSmall ? 'text-[10px]' : 'text-xs'} font-semibold text-primary/80 ${className}`}>
      <EyraOrb className={isSmall ? 'h-5 w-5' : 'h-6 w-6'} decorative={false} />
      {label}
    </span>
  );
}

/** Standalone "Powered by EYRA" footer line — use under search boxes, results, etc. */
export function EyraPoweredBy({ label = 'Powered by EYRA', className = '' }) {
  return (
    <div className={`flex items-center justify-center gap-1.5 ${className}`}>
      <EyraOrb className="h-5 w-5 opacity-70" decorative={false} />
      <span className="text-[10px] text-muted-foreground/60 font-medium tracking-wide">{label}</span>
    </div>
  );
}

/** Section header label — "EYRA Funding Intelligence", "EYRA Project Twin", etc. */
export function EyraSectionLabel({ label, className = '' }) {
  return (
    <div className={`flex items-center gap-2 ${className}`}>
      <EyraOrb className="h-6 w-6" decorative={false} />
      <span className="text-[10px] font-bold uppercase tracking-widest text-primary">{label}</span>
    </div>
  );
}
